name: Run SpiceCode Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Use a Python version compatible with your project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest typer
        # Note: Ideally, you should fix your requirements.txt and use:
        # pip install .
        # Or at least:
        # pip install -r requirements.txt
        # But due to the encoding and importlib issues observed,
        # installing specific dependencies needed for tests directly for now.

    - name: Run tests
      run: |
        python -m pytest tests/analyze_all_langs/